/**
 * Shared types for the GitSplits Hybrid "Brain + Muscle" Architecture.
 * Used for communication between the Controller (Brain) and Worker (Muscle).
 */

export interface Contributor {
  username: string;
  commits: number;
  percentage: number;
}

/**
 * The raw report payload generated by the Worker (EigenCompute).
 */
export interface ContributionReport {
  repoUrl: string;
  contributors: Contributor[];
  aiAnalysis: string;
  aiSignature: string;
  workerAddress: string;
  timestamp: number;
  nonce: string;
}

/**
 * The envelope containing the report and its cryptographic proof of origin.
 */
export interface SignedContributionReport {
  report: ContributionReport;
  signature: string;
  attestation?: {
    type: 'eigencompute' | 'dstack' | 'mock';
    quote?: string;
  };
}

/**
 * Multi-dimensional quality assessment for a contributor.
 * Float scores (0.0–1.0) enable weighted split allocations
 * instead of binary pass/fail decisions.
 */
export interface ContributorQuality {
  username: string;
  /** 0.0–1.0: Overall quality score combining all signals */
  quality: number;
  /** 0.0–1.0: Confidence that commit counts reflect genuine contribution value */
  commitConfidence: number;
  /** Routing action for split allocation */
  creditAction: 'full_credit' | 'partial_credit' | 'no_credit' | 'flag_for_review';
  /** Reasons for the assessment */
  reasons: string[];
}

/**
 * Common message types for the Agent system
 */
export type AgentMessageType = 'cast' | 'dm' | 'web';

export interface AgentMessage {
  text: string;
  author: string;
  type: AgentMessageType;
  walletAddress?: string;
  nearAccountId?: string;
  evmAddress?: string;
}
