/**
 * Shared types for the GitSplits Hybrid "Brain + Muscle" Architecture.
 * Used for communication between the Controller (Brain) and Worker (Muscle).
 */

export interface Contributor {
  username: string;
  commits: number;
  percentage: number;
}

/**
 * The raw report payload generated by the Worker (EigenCompute).
 */
export interface ContributionReport {
  repoUrl: string;
  contributors: Contributor[];
  aiAnalysis: string;
  aiSignature: string;
  workerAddress: string;
  timestamp: number;
  nonce: string;
}

/**
 * The envelope containing the report and its cryptographic proof of origin.
 */
export interface SignedContributionReport {
  report: ContributionReport;
  signature: string;
  attestation?: {
    type: 'eigencompute' | 'dstack' | 'mock';
    quote?: string;
  };
}

/**
 * Common message types for the Agent system
 */
export type AgentMessageType = 'cast' | 'dm' | 'web';

export interface AgentMessage {
  text: string;
  author: string;
  type: AgentMessageType;
  walletAddress?: string;
  nearAccountId?: string;
  evmAddress?: string;
}
